package truongtn.entity;
// Generated Jan 21, 2020 8:50:57 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Account generated by hbm2java
 */
public class Account  implements java.io.Serializable {


     private String email;
     private String name;
     private String password;
     private String role;
     private String status;
     private Set<Article> articles = new HashSet<Article>(0);
     private Set<Comment> comments = new HashSet<Comment>(0);
     private String facebookID;

    public Account() {
    }

    public Account(String email, String name) {
        this.email = email;
        this.name = name;
    }

    public Account(String email, String name, String facebookID) {
        this.email = email;
        this.name = name;
        this.facebookID = facebookID;
    }

    public Account(String email, String name, String password, String role, String status, String facebookID) {
        this.email = email;
        this.name = name;
        this.password = password;
        this.role = role;
        this.status = status;
        this.facebookID = facebookID;
    }
	
    
    public Account(String email, String name, String password, String role, String status) {
        this.email = email;
        this.name = name;
        this.password = password;
        this.role = role;
        this.status = status;
    }
    public Account(String email, String name, String password, String role, String status, Set<Article> articles, Set<Comment> comments) {
       this.email = email;
       this.name = name;
       this.password = password;
       this.role = role;
       this.status = status;
       this.articles = articles;
       this.comments = comments;
    }
   
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set<Article> getArticles() {
        return this.articles;
    }
    
    public void setArticles(Set<Article> articles) {
        this.articles = articles;
    }
    public Set<Comment> getComments() {
        return this.comments;
    }
    
    public void setComments(Set<Comment> comments) {
        this.comments = comments;
    }

    public String getFacebookID() {
        return facebookID;
    }

    public void setFacebookID(String fbID) {
        this.facebookID = fbID;
    }


}


