package truongtn.entity;
// Generated Jan 21, 2020 8:50:57 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Article generated by hbm2java
 */
public class Article  implements java.io.Serializable {


     private int id;
     private Account account;
     private String title;
     private String shortDescription;
     private String content;
     private Date postingDate;
     private String status;
     private Set<Comment> comments = new HashSet<Comment>(0);

    public Article() {
    }

    public Article(Account account, String title, String shortDescription, String content, Date postingDate, String status) {
        this.account = account;
        this.title = title;
        this.shortDescription = shortDescription;
        this.content = content;
        this.postingDate = postingDate;
        this.status = status;
    }
    
	
    public Article(int id, Account account, String title, String shortDescription, String content, Date postingDate, String status) {
        this.id = id;
        this.account = account;
        this.title = title;
        this.shortDescription = shortDescription;
        this.content = content;
        this.postingDate = postingDate;
        this.status = status;
    }
    public Article(int id, Account account, String title, String shortDescription, String content, Date postingDate, String status, Set<Comment> comments) {
       this.id = id;
       this.account = account;
       this.title = title;
       this.shortDescription = shortDescription;
       this.content = content;
       this.postingDate = postingDate;
       this.status = status;
       this.comments = comments;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getShortDescription() {
        return this.shortDescription;
    }
    
    public void setShortDescription(String shortDescription) {
        this.shortDescription = shortDescription;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public Date getPostingDate() {
        return this.postingDate;
    }
    
    public void setPostingDate(Date postingDate) {
        this.postingDate = postingDate;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set<Comment> getComments() {
        return this.comments;
    }
    
    public void setComments(Set<Comment> comments) {
        this.comments = comments;
    }




}


