package truongtn.entity;
// Generated Jan 21, 2020 8:50:57 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Comment generated by hbm2java
 */
public class Comment  implements java.io.Serializable {


     private int idComment;
     private Account account;
     private Article article;
     private String content;
     private Date time;

    public Comment() {
    }

    public Comment(Account account, Article article, String content, Date time) {
        this.account = account;
        this.article = article;
        this.content = content;
        this.time = time;
    }
    
    public Comment(int idComment, Account account, Article article, String content, Date time) {
       this.idComment = idComment;
       this.account = account;
       this.article = article;
       this.content = content;
       this.time = time;
    }
   
    public int getIdComment() {
        return this.idComment;
    }
    
    public void setIdComment(int idComment) {
        this.idComment = idComment;
    }
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }
    public Article getArticle() {
        return this.article;
    }
    
    public void setArticle(Article article) {
        this.article = article;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }

}